
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: michalbork3@gmail.com
    password: trcobtqsackqtwvj
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/kantor?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:sammy}
    password: ${JDBC_DATABASE_PASSWORD:password}
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true



